// Generated by wxt
export {}
declare global {
  const ContentScriptContext: typeof import('wxt/utils/content-script-context')['ContentScriptContext']
  const FavoritesButtonPortal: typeof import('/Users/khk4912/Code/Chzzk-PIP/components/FavoriteAddButton')['FavoritesButtonPortal']
  const FavoritesListPortal: typeof import('/Users/khk4912/Code/Chzzk-PIP/components/FavoritesList')['FavoritesListPortal']
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns')['InvalidMatchPattern']
  const MatchPattern: typeof import('wxt/utils/match-patterns')['MatchPattern']
  const PIPPortal: typeof import('/Users/khk4912/Code/Chzzk-PIP/components/pip_button')['PIPPortal']
  const RecordOverlayPortal: typeof import('/Users/khk4912/Code/Chzzk-PIP/components/rec_overlay')['RecordOverlayPortal']
  const RecordPortal: typeof import('/Users/khk4912/Code/Chzzk-PIP/components/rec_button')['RecordPortal']
  const RecordStateContext: typeof import('/Users/khk4912/Code/Chzzk-PIP/utils/record_info_helper')['RecordStateContext']
  const ScreenShotPortal: typeof import('/Users/khk4912/Code/Chzzk-PIP/components/screenshot_button')['ScreenShotPortal']
  const SeekPortal: typeof import('/Users/khk4912/Code/Chzzk-PIP/components/seek')['SeekPortal']
  const ThemeContextProvider: typeof import('/Users/khk4912/Code/Chzzk-PIP/utils/theme_context')['ThemeContextProvider']
  const browser: typeof import('wxt/browser')['browser']
  const createDraggablePreview: typeof import('/Users/khk4912/Code/Chzzk-PIP/utils/screenshot_preview')['createDraggablePreview']
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe')['createIframeUi']
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated')['createIntegratedUi']
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root')['createShadowRootUi']
  const defineAppConfig: typeof import('wxt/utils/define-app-config')['defineAppConfig']
  const defineBackground: typeof import('wxt/utils/define-background')['defineBackground']
  const defineContentScript: typeof import('wxt/utils/define-content-script')['defineContentScript']
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script')['defineUnlistedScript']
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin')['defineWxtPlugin']
  const download: typeof import('/Users/khk4912/Code/Chzzk-PIP/utils/download')['download']
  const fakeBrowser: typeof import('wxt/testing')['fakeBrowser']
  const getRecordInfo: typeof import('/Users/khk4912/Code/Chzzk-PIP/utils/record_info_helper')['getRecordInfo']
  const getStreamInfo: typeof import('/Users/khk4912/Code/Chzzk-PIP/utils/stream_info')['getStreamInfo']
  const getTempBlobURL: typeof import('/Users/khk4912/Code/Chzzk-PIP/utils/record_info_helper')['getTempBlobURL']
  const injectScript: typeof import('wxt/utils/inject-script')['injectScript']
  const isClipPage: typeof import('/Users/khk4912/Code/Chzzk-PIP/utils/download')['isClipPage']
  const isLivePage: typeof import('/Users/khk4912/Code/Chzzk-PIP/utils/download')['isLivePage']
  const isMoz: typeof import('/Users/khk4912/Code/Chzzk-PIP/utils/download')['isMoz']
  const isShortsPage: typeof import('/Users/khk4912/Code/Chzzk-PIP/utils/download')['isShortsPage']
  const isVODPage: typeof import('/Users/khk4912/Code/Chzzk-PIP/utils/download')['isVODPage']
  const koreanToEnglish: typeof import('/Users/khk4912/Code/Chzzk-PIP/utils/hooks')['koreanToEnglish']
  const sanitizeFileName: typeof import('/Users/khk4912/Code/Chzzk-PIP/utils/save')['sanitizeFileName']
  const seekLeft: typeof import('/Users/khk4912/Code/Chzzk-PIP/utils/seek')['seekLeft']
  const seekRight: typeof import('/Users/khk4912/Code/Chzzk-PIP/utils/seek')['seekRight']
  const segmentize: typeof import('/Users/khk4912/Code/Chzzk-PIP/utils/transcode')['segmentize']
  const setMaxHQ: typeof import('/Users/khk4912/Code/Chzzk-PIP/utils/max_hq')['setMaxHQ']
  const setRecordInfo: typeof import('/Users/khk4912/Code/Chzzk-PIP/utils/record_info_helper')['setRecordInfo']
  const setTempBlobURL: typeof import('/Users/khk4912/Code/Chzzk-PIP/utils/record_info_helper')['setTempBlobURL']
  const startHighFrameRateRecord: typeof import('/Users/khk4912/Code/Chzzk-PIP/utils/record')['startHighFrameRateRecord']
  const startRecord: typeof import('/Users/khk4912/Code/Chzzk-PIP/utils/record')['startRecord']
  const stopRecord: typeof import('/Users/khk4912/Code/Chzzk-PIP/utils/record')['stopRecord']
  const storage: typeof import('wxt/utils/storage')['storage']
  const toGIF: typeof import('/Users/khk4912/Code/Chzzk-PIP/utils/transcode')['toGIF']
  const toMP4: typeof import('/Users/khk4912/Code/Chzzk-PIP/utils/transcode')['toMP4']
  const toMP4AAC: typeof import('/Users/khk4912/Code/Chzzk-PIP/utils/transcode')['toMP4AAC']
  const toWEBP: typeof import('/Users/khk4912/Code/Chzzk-PIP/utils/transcode')['toWEBP']
  const trim: typeof import('/Users/khk4912/Code/Chzzk-PIP/utils/transcode')['trim']
  const useAppConfig: typeof import('wxt/utils/app-config')['useAppConfig']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useEffect: typeof import('react')['useEffect']
  const useFFmpeg: typeof import('/Users/khk4912/Code/Chzzk-PIP/utils/transcode')['useFFmpeg']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useShortcut: typeof import('/Users/khk4912/Code/Chzzk-PIP/utils/hooks')['useShortcut']
  const useState: typeof import('react')['useState']
  const useThemeContext: typeof import('/Users/khk4912/Code/Chzzk-PIP/utils/theme_context')['useThemeContext']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
}
