// Generated by wxt
import 'wxt/browser'

declare module 'wxt/browser' {
  export type PublicPath =
    | ''
    | '/'
    | '/background.js'
    | '/content-scripts/content.js'
    | '/ffmpeg/ffmpeg-core.js'
    | '/ffmpeg/ffmpeg-core.wasm'
    | '/ffmpeg/ffmpeg-core.worker.js'
    | '/monkeypatch/seek.js'
    | '/popup.html'
    | '/record_result.html'
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
